### ISSUE TITLE
beekeeper panics on multiple inheretance

### ISSUE THREAD

**Issue by vandot** [ethersphere/beekeeper#149]
tried in config `bootnode-local-dns` inherits `bootnode-local` that inherits `bee-local`
```
  bee-local:
    _inherit: ""
  bootnode-local:
    _inherit: "bee-local"
    bootnode-mode: true
  bee-local-dns:
    _inherit: "bee-local"
    bootnode: /dnsaddr/localhost
  bootnode-local-dns:
    _inherit: "bootnode-local"
    bootnode: /dnsaddr/localhost
```

```
panic: runtime error: index out of range [1] with length 1

goroutine 19 [running]:
github.com/ethersphere/beekeeper/pkg/k8s/bee.parsePort(0x0, 0x0, 0x1c9f2f0, 0x29, 0xc0003ea8a8)
    github.com/ethersphere/beekeeper/pkg/k8s/bee/helpers.go:408 +0xce
github.com/ethersphere/beekeeper/pkg/k8s/bee.(*Client).Create(0xc0000a2ca8, 0x20062e0, 0xc00009d980, 0x0, 0x0, 0x0, 0xc000116e80, 0x74, 0x1, 0x0, ...)
    github.com/ethersphere/beekeeper/pkg/k8s/bee/bee.go:107 +0xc7b
github.com/ethersphere/beekeeper/pkg/bee.(*NodeGroup).CreateNode(0xc0001cad00, 0x20062e0, 0xc00009d980, 0xc000023154, 0xa, 0x0, 0x0)
    github.com/ethersphere/beekeeper/pkg/bee/nodegroup.go:262 +0x598
github.com/ethersphere/beekeeper/pkg/bee.(*NodeGroup).SetupNode(0xc0001cad00, 0x20062e0, 0xc00009d980, 0xc000023154, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    github.com/ethersphere/beekeeper/pkg/bee/nodegroup.go:651 +0x1ba
github.com/ethersphere/beekeeper/cmd/beekeeper/cmd.(*command).setupCluster.func1(0x0, 0x0)
    github.com/ethersphere/beekeeper/cmd/beekeeper/cmd/cluster.go:120 +0xbd
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000221f50, 0xc000312360)
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
make: *** [Makefile:39: deploylocal] Error 2
Error: Process completed with exit code 2.
```
